import React, { useState } from 'react';
import { X, Check, FilePlus2 } from 'lucide-react';

const AnalysisReviewModal = ({ update, onClose, onConfirm }) => {
    // In a real app, this summary would be generated by an AI call
    const [aiSummary, setAiSummary] = useState(
        `This document outlines new transaction monitoring standards for Payment Service Providers (PSPs).\n\nKey Changes:\n1. Real-time monitoring is now required for transactions exceeding NGN 5,000,000.\n2. Monthly submission of Form 1025 is now mandatory.\n3. All FSPs must attest to these new guidelines by Q3.\n\nSuggested Action: Create a new rule in the Rules Engine to reflect the new transaction threshold.`
    );

    const handleConfirm = () => {
        // This would trigger the "flywheel" effect we discussed
        onConfirm(update);
        onClose();
    };

    return (
        <div className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-50 animate-fade-in-fast">
            <div className="bg-[#1e252d] rounded-2xl shadow-2xl p-6 w-full max-w-3xl text-white">
                <div className="flex justify-between items-center mb-4 border-b border-gray-700 pb-3">
                    <h3 className="text-2xl font-bold text-[#c0933e]">AI Analysis & Review</h3>
                    <button onClick={onClose} className="p-1 rounded-full text-gray-400 hover:bg-gray-700 hover:text-white">
                        <X size={24} />
                    </button>
                </div>
                <div className="space-y-4">
                    <div>
                        <p className="text-sm font-medium text-gray-400">Source Document:</p>
                        <p className="font-bold">{update.title}</p>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">AI-Generated Summary & Suggested Action</label>
                        <textarea
                            rows={8}
                            value={aiSummary}
                            onChange={(e) => setAiSummary(e.target.value)}
                            className="w-full p-2 border border-gray-600 rounded-md bg-gray-800 text-white focus:ring-[#c0933e] focus:border-[#c0933e]"
                        />
                         <p className="text-xs text-gray-500 mt-1">You can edit this summary before confirming.</p>
                    </div>
                </div>
                <div className="flex justify-end pt-6 mt-6 border-t border-gray-700">
                    <button type="button" onClick={onClose} className="bg-gray-600 py-2 px-4 rounded-md text-sm font-medium hover:bg-gray-700 mr-2">
                        Cancel
                    </button>
                    <button 
                        type="button" 
                        onClick={handleConfirm} 
                        className="bg-green-600 text-white font-bold py-2 px-4 rounded-md text-sm hover:bg-green-500 flex items-center"
                    >
                        <Check size={16} className="mr-2"/> Confirm & Create Rule
                    </button>
                </div>
            </div>
        </div>
    );
};

export default AnalysisReviewModal;
